version: "3.9"
services:
  wb-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: wb-app
    container_name: wb-app
    restart: unless-stopped
    tty: true
    volumes:
      - ./wb-back:/var/www/wb-back
    networks:
      - app-network

  webserver:
    image: nginx:alpine
    container_name: nginx-wb-app
    restart: unless-stopped
    tty: true
    ports:
      - "8082:80"
    volumes:
      - ./wb-back:/var/www/wb-back
      - ./nginx/conf.d:/etc/nginx/conf.d/
      - ./nginx/snippets:/etc/nginx/snippets
    networks:
      - app-network

  db:
    image: postgres:16
    container_name: postgres-wb-app
    restart: unless-stopped
    tty: true
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: wb_app
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpassword
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
