version: "3.9"
services:
  wb-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: wb-app
    container_name: wb-app
    restart: unless-stopped
    tty: true
    volumes:
      - ./wb-back:/var/www/wb-back
    networks:
      - app-network

  webserver:
    image: nginx:alpine
    container_name: nginx-wb-app
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"  # Changed the port to 8083 to avoid conflict
      - "443:443"
    volumes:
      - ./wb-back:/var/www/wb-back
      - ./nginx/conf.d:/etc/nginx/conf.d/
      - ./nginx/certs:/etc/nginx/certs/
      - ./nginx/snippets:/etc/nginx/snippets
    networks:
      - app-network

  db:
    image: postgres:16
    container_name: postgres-wb-app
    restart: unless-stopped
    tty: true
    ports:
      - "5433:5432"  # Changed the port to 5433 to avoid conflict
    environment:
      POSTGRES_DB: wb_app
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpassword
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - app-network

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scheduler
    user: "33:33" # Ensure container runs as www-data user
    volumes:
      - ./wb-back:/var/www/wb-back
    depends_on:
      - wb-app
      - db
    networks:
      - app-network
    env_file:
      - ./wb-back/.env
    command: >
      sh -c "
      sleep 10 &&
      /usr/local/bin/cron-schedule.sh"
    restart: always

  queue-worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: queue-worker
    user: "33:33" # Ensure container runs as www-data user
    volumes:
      - ./wb-back:/var/www/wb-back
    depends_on:
      - wb-app
      - db
    networks:
      - app-network
    env_file:
      - ./wb-back/.env
    command: >
      sh -c "
      sleep 10 &&
      php /var/www/wb-back/artisan queue:work --tries=3 --max-time=3600"
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local