<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateFeedbacksTable extends Migration
{
    public function up()
    {
        Schema::create('feedbacks', function (Blueprint $table) {
            $table->id();
            $table->foreignId('cabinet_id')->constrained()->onDelete('cascade'); // Reference to the cabinet
            $table->string('feedback_id')->unique(); // ID from the API
            $table->text('text'); // The feedback text
            $table->integer('productValuation'); // The product rating
            $table->dateTime('createdDate'); // When the feedback was created
            $table->text('answer')->nullable(); // Autogenerated answer
            $table->enum('status', ['not_sent', 'sent', 'processing', 'ready_to_send'])->default('not_sent'); // Status of the answer
            $table->json('productDetails'); // JSON column to store product details
            $table->json('photoLinks')->nullable(); // JSON column for photo links
            $table->boolean('wasViewed')->default(false); // Whether the feedback was viewed
            $table->string('userName'); // The user name who provided feedback
            $table->string('color')->nullable(); // Color of the product
            $table->integer('subjectId'); // Subject ID from the feedback
            $table->string('subjectName')->nullable(); // Name of the subject
            $table->timestamps(); // Created and updated timestamps
        });
    }

    public function down()
    {
        Schema::dropIfExists('feedbacks');
    }
}
